### ISSUE TITLE
Improve the Fun Cog

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#18]
Add commands to see pictures of dogs, cats, and ducks using publicly available free APIs.

**Comment by aadi-1024** [comment]
I opened a WIP pull request that implements the dog command with #33

I'd be happy to add a cat command as well once i know whether my code is good enough!

**Comment by Aryan-401** [comment]
The screenshots you attached in the Closed PR look good to me. Don't forget to fetch upstream since allot of changes have been made since you last forked

**Comment by aadi-1024** [comment]
Yes! Opened a new PR #39 after rebasing the fork and adding a cat command.

**Comment by Aryan-401** [comment]
You forgot the third animal @aadi-1024

**Comment by aadi-1024** [comment]
I will add it today after classes :D

**Comment by aadi-1024** [comment]
It's done!
