### ISSUE TITLE
Add a single Role to multiple People

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#22]
Create a command in moderation.py that allows an admin to give multiple roles (separated by spaces) to a single User. Make sure the permissions allow only admins and users with manage roles permission to access it

**Comment by sagamantus** [comment]
Hey! I would love to implement this command.
Correct me if I'm wrong, the command would go in `cogs/moderation.py`.

**Comment by Aryan-401** [comment]
Yes it would

**Comment by sagamantus** [comment]
Just noticed that the title says giving **one role to multiple members** whereas the description says giving **multiple roles to a single member**. So, am I supposed to implement both of them or just the one mentioned in the description?

**Comment by Aryan-401** [comment]
Oh, I'm sorry for the gap in communication, you have to implement a command which takes input as 1 role, and adds it to multiple tagged users, separated by spaces

**Comment by sagamantus** [comment]
Alright. I'm on it!
