### ISSUE TITLE
Add .horoscope command

### ISSUE THREAD

**Issue by satyamrs00** [MicrosoftStudentChapter/Hack-O-Bot#23]
#### Public API Resource
https://aztro.readthedocs.io/en/latest/

#### Description
The API retrieves daily horoscopes for yesterday, today, and tomorrow. It requires name of sign like aries, taurus, gemini, cancer, leo, virgo, libra, scorpio, sagittarius, capricorn, aquarius and pisces.

**Comment by Aryan-401** [comment]
@satyamrs00 do you want to work on the command? One idea I had was using the `User.created_at` function to find a user's "Discord" Horoscope. 

https://discordpy.readthedocs.io/en/latest/api.html#discord.User.created_at

Feel free to ideate and create your own command

**Comment by satyamrs00** [comment]
yes I would like to work on this 
and I liked the idea of "discord horoscope"
then we need to change the command name to something like ".d-horoscope" or ".doroscope" because ".horoscope" would be misleading

tell me what name it should have , then I will start

**Comment by Aryan-401** [comment]
I think `horoscope` should be fine. Just make sure to clarify in the help parameter. Also make sure to add this to `cogs/fun.py`.

**Comment by satyamrs00** [comment]
![image](https://user-images.githubusercontent.com/96380323/194932719-dfa0ddb3-f8ea-4622-a939-d8bdf758e2be.png)
![image](https://user-images.githubusercontent.com/96380323/194932733-0263894c-f91b-46ad-ae0b-f677c6f3f875.png)

is this alright ?

**Comment by Aryan-401** [comment]
Yup it looks alright, one change would be to change the embed color to blurple
