### ISSUE TITLE
Send the prefix of the bot whenever it is Tagged 

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#28]
allow the bot to send its prefix in an embed when it is tagged.
Note: It will only send its prefix when the only content of the message is the Tag. If any other text follows, the bot will not return anything.

**Comment by KidesLeo** [comment]
About to work on this even though I'm new to discord bots, is that okay?

**Comment by Aryan-401** [comment]
Sure thing! Here is a link to the documentation!

https://discordpy.readthedocs.io/en/latest/api.html

**Comment by KidesLeo** [comment]
I wasn't sure what to say in the embed, is this alright?
`Yes? Use the '.' prefix to give me commands.`
![image](https://user-images.githubusercontent.com/39452009/194936787-e19f8323-bfa2-404a-9ece-73481744eb2a.png)

**Comment by Aryan-401** [comment]
How about
"Hi there! Use `.help` for a full list of commands."
Also change the color of the embed to Blurple


Otherwise, it looks good! Please do check it works on mobile too

**Comment by KidesLeo** [comment]
All done, opened a PR.
