### ISSUE TITLE
Add a contributors command 

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#36]
Create a command in `discord_main.py` to display everyone who has contributed to the discord bot. Also, link their Github Profiles

**Comment by Ayushi8989** [comment]
@Aryan-401 I would like to give this one a try.

**Comment by Aryan-401** [comment]
Alright @Ayushi8989

**Comment by Aryan-401** [comment]
Hi, since this is a public repository, would it not be possible to get the data without using a personal access token?

**Comment by Ayushi8989** [comment]
Hey @Aryan-401, the `GITHUB_TOKEN` is optional. The command will work even without the `GITHUB_TOKEN` environment variable. There is a limit of [60 requests per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts) for unauthenticated requests, whereas the authenticated ones get a limit of 5,000 requests per hour. I can try limiting the number of requests using some caching, but I recommend adding a personal access token.

**Comment by Aryan-401** [comment]
Since the bot is just starting, the hard limit won't be that much of an Issue. For the time being, can you remove the `GITHUB_TOKEN` environment variable? If necessary, we can adapt to the change by changing the code later on. 

Make sure to add an error block if the request returns a non-200 status code

**Comment by Ayushi8989** [comment]
Alright, I'll make the necessary changes.
