### ISSUE TITLE
Find out who is the richest person according to Forbes

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#38]
According to Forbes, create a command that shows who the wealthiest person is. Also, tell their net worth in USD

**Comment by ghost** [comment]
I am Interested in this issue.

**Comment by satyamrs00** [comment]
hey i can do this
if no one is assigned yet

**Comment by Aryan-401** [comment]
Great! You can go ahead with this command @satyamrs00

**Comment by satyamrs00** [comment]
does this command go under any category ? 
I am putting it in fun for now

**Comment by Aryan-401** [comment]
Yup `fun.py`

**Comment by satyamrs00** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/96380323/195890426-46b9bea1-5f69-4312-8422-af82bdb7fc5a.png">
is this alright ?

**Comment by Aryan-401** [comment]
How about a photo of him as the `embed.set_thumbnail()`
