### ISSUE TITLE
Display About Server Command

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#40]
In `cogs/moderation.py`, create a command which shows basic details about the server the command is run in. This should include, but is not limited to:

Name of server
When It was created
How many members
How many roles have been used (out of 250)
How many channels have been used up (Both Voice and Text)

**Comment by 90r1ll4** [comment]
@Aryan-401 please assign this to me, i want to try it

**Comment by Aryan-401** [comment]
Alright 👍🏻

**Comment by 90r1ll4** [comment]
@Aryan-401 raised the PR kindly check
