### ISSUE TITLE
Add commands list in readme 

### ISSUE THREAD

**Issue by satyamrs00** [MicrosoftStudentChapter/Hack-O-Bot#46]
I think we should add a table of available commands in readme so that anyone suggesting a new command doesnt suggest a duplicate 

also it will be good to keep track of the commands

**Comment by Aryan-401** [comment]
Seems like a good Idea

**Comment by satyamrs00** [comment]
and i want to do this one

**Comment by Aryan-401** [comment]
Sure thing!
