### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#5]
In the `discord_main.py` file, create a catch-all error using the `on_command_error` to alert the user whenever they input the arguments with proper fixes

**Comment by satyamrs00** [comment]
I am doing this one now

**Comment by Aryan-401** [comment]
You can only work on one issue at a time. Please Finish your current Issue

**Comment by Ave-Eren** [comment]
I'm willing to take this up
