### ISSUE TITLE
Custom Help Command

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#6]
The default Help command is so boring, let's bring life to a new one using embeds and the CustomHelpCommand class. Create help commands for commands and cogs

**Comment by satyamrs00** [comment]
I want to do this now
can you assign it to me

**Comment by satyamrs00** [comment]
Does this look good ? 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/96380323/194727455-54596d7f-be26-4e83-9382-e7b00fd5c61b.png">

**Comment by satyamrs00** [comment]
@Aryan-401

**Comment by Aryan-401** [comment]
![image](https://user-images.githubusercontent.com/58473359/194728044-8d07a105-7a26-4e93-bcb3-a2faf1167980.png)

I was looking for something like this.

**Comment by satyamrs00** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/96380323/194729250-7e92459d-19fe-4e6d-807a-c9beeb87b14e.png">
take a look

**Comment by Aryan-401** [comment]
Does Look alright, make a PR and ill look trough the code, before finally merging
