### ISSUE TITLE
Hello Message when Entering Server

### ISSUE THREAD

**Issue by Aryan-401** [MicrosoftStudentChapter/Hack-O-Bot#7]
Display a message in every server the bot joins. Just to say Hi :)

**Comment by OjashKush** [comment]
Assign me this

**Comment by Aryan-401** [comment]
Alright @OjashKush ! Be sure to prettify it in an embed. First impressions are important after all

**Comment by Aryan-401** [comment]
@OjashKush here are a few improvements

1. How about wrapping this all under an Embed,
2. Instead of hardcoding the channel, implement it in such a manner to send it in the channel which has "general" in the channel_name.lower().
e.g., If a server has "General Chat" as a channel name, it'll send it in instead of searching for only "general."
 
 3. use f-strings wherever possible. The .format() is a relic of  the Python 2.X days
